#!/usr/bin/env python3
"""Dependency-free local maintenance CLI for Team Engram."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import re
import sys
from collections import defaultdict
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import quote, unquote, urlsplit

BRAIN_DIRECTORY = "Engram"
INDEX_NAME = "INDEX.md"
GENERATED_MARKER = "<!-- generated by Tools/engram.py; do not edit -->"
SCHEMA_PATH = Path("Schemas/team-engram.schema.json")
CONTENT_DIRECTORIES = {
    "Knowledge": "knowledge",
    "Decisions": "decision",
    "Sources/Raw": "source-raw",
    "Sources/Records": "source-record",
}
EMPTY_VALUES = {"", "[]", "{}", "none", "null", "n/a", "na", "unknown", "todo", "tbd"}


@dataclass(frozen=True)
class FrontMatter:
    metadata: dict[str, Any]
    body: str
    has_frontmatter: bool = False
    error: str | None = None
    error_line: int | None = None
    body_start_line: int = 1


@dataclass(frozen=True)
class IndexEntry:
    document_type: str
    title: str
    status: str
    topics: tuple[str, ...]
    summary: str
    relative_path: str


@dataclass(frozen=True)
class LintIssue:
    severity: str
    path: Path
    line: int
    message: str


def workspace_root() -> Path:
    return Path(__file__).resolve().parent.parent


def read_utf8(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def load_schema(root: Path) -> dict[str, Any]:
    """Load the canonical JSON schema using only the standard library."""
    with (root / SCHEMA_PATH).open(encoding="utf-8") as handle:
        schema = json.load(handle)
    if schema.get("schema_version") != 1 or not isinstance(schema.get("types"), dict):
        raise ValueError(f"unsupported or malformed schema: {SCHEMA_PATH.as_posix()}")
    return schema


def _strip_yaml_comment(value: str) -> str:
    quote_character: str | None = None
    escaped = False
    for index, character in enumerate(value):
        if escaped:
            escaped = False
            continue
        if character == "\\" and quote_character == '"':
            escaped = True
            continue
        if character in {"'", '"'}:
            quote_character = None if quote_character == character else character if quote_character is None else quote_character
        elif character == "#" and quote_character is None and (index == 0 or value[index - 1].isspace()):
            return value[:index].rstrip()
    return value.rstrip()


def _parse_scalar(raw_value: str) -> tuple[Any, str | None]:
    value = _strip_yaml_comment(raw_value).strip()
    if not value:
        return None, None
    if value.startswith("["):
        if not value.endswith("]"):
            return None, "unterminated inline list"
        try:
            parsed = ast.literal_eval(value)
        except (SyntaxError, ValueError):
            # YAML permits unquoted simple list items; quote them one at a time.
            inner = value[1:-1].strip()
            if not inner:
                return [], None
            parsed = [_parse_scalar(item.strip())[0] for item in inner.split(",")]
        if not isinstance(parsed, (list, tuple)):
            return None, "inline list must contain a list"
        return list(parsed), None
    if value[0] in {"'", '"'}:
        if len(value) < 2 or value[-1] != value[0]:
            return None, "unterminated quoted value"
        try:
            return ast.literal_eval(value), None
        except (SyntaxError, ValueError):
            return None, "malformed quoted value"
    lowered = value.casefold()
    if lowered in {"null", "~"}:
        return None, None
    if lowered in {"true", "false"}:
        return lowered == "true", None
    return value, None


def parse_frontmatter(text: str) -> FrontMatter:
    """Parse the top-level scalar/list YAML subset used by Team Engram."""
    text = text.lstrip("\ufeff")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return FrontMatter({}, text)
    closing_index = next((index for index in range(1, len(lines)) if lines[index].strip() == "---"), None)
    if closing_index is None:
        return FrontMatter({}, "", True, "unterminated YAML frontmatter", 1, len(lines) + 1)

    metadata: dict[str, Any] = {}
    current_key: str | None = None
    for index in range(1, closing_index):
        line = lines[index]
        line_number = index + 1
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line[0].isspace():
            if current_key is None or not stripped.startswith("-"):
                return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, "unexpected indentation in YAML frontmatter", line_number, closing_index + 2)
            parsed, error = _parse_scalar(stripped[1:].strip())
            if error:
                return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, error, line_number, closing_index + 2)
            previous = metadata.get(current_key)
            if previous is None:
                previous = []
                metadata[current_key] = previous
            if not isinstance(previous, list):
                return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, f"list item follows scalar field '{current_key}'", line_number, closing_index + 2)
            previous.append(parsed)
            continue
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_.-]*):(?:\s*(.*))?$", line)
        if not match:
            return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, "expected a top-level 'key: value' field", line_number, closing_index + 2)
        key, raw_value = match.group(1), match.group(2) or ""
        if key in metadata:
            return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, f"duplicate YAML field '{key}'", line_number, closing_index + 2)
        parsed, error = _parse_scalar(raw_value)
        if error:
            return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, error, line_number, closing_index + 2)
        metadata[key] = parsed
        current_key = key
    return FrontMatter(metadata, "\n".join(lines[closing_index + 1 :]), True, body_start_line=closing_index + 2)


def _is_meaningful(value: Any) -> bool:
    if value is None or value is False:
        return False
    if isinstance(value, (list, tuple, set)):
        return any(_is_meaningful(item) for item in value)
    if isinstance(value, dict):
        return any(_is_meaningful(item) for item in value.values())
    return str(value).strip().strip("\"'").casefold() not in EMPTY_VALUES


def _metadata_strings(value: Any) -> list[str]:
    if isinstance(value, str) and _is_meaningful(value):
        return [value.strip()]
    if isinstance(value, list):
        return [item.strip() for item in value if isinstance(item, str) and _is_meaningful(item)]
    return []


def _first_h1(body: str) -> str:
    in_fence = False
    marker = ""
    for line in body.splitlines():
        fence = re.match(r"^\s*(```|~~~)", line)
        if fence:
            if not in_fence:
                in_fence, marker = True, fence.group(1)
            elif fence.group(1) == marker:
                in_fence = False
            continue
        if not in_fence:
            match = re.match(r"^#\s+(.+?)\s*#*\s*$", line)
            if match:
                return match.group(1).strip()
    return ""


def _clean_inline_markdown(text: str) -> str:
    text = re.sub(r"!\[([^]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    return re.sub(r"\s+", " ", re.sub(r"[*_~]+", "", text)).strip()


def _first_summary(body: str, limit: int = 220) -> str:
    paragraph: list[str] = []
    in_fence = False
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if re.match(r"^(```|~~~)", line):
            in_fence = not in_fence
            continue
        if in_fence or line.startswith("<!--") or line.startswith("> [!"):
            continue
        if not line:
            if paragraph:
                break
            continue
        if re.match(r"^#{1,6}\s+", line) or re.match(r"^(?:[-+*]|\d+[.)])\s+", line):
            if paragraph:
                break
            continue
        paragraph.append(line.lstrip("> "))
    summary = _clean_inline_markdown(" ".join(paragraph))
    if len(summary) <= limit:
        return summary
    return summary[: limit + 1].rsplit(" ", 1)[0].rstrip() + "…"


def _corpus_markdown_files(root: Path) -> list[Path]:
    corpus = root / BRAIN_DIRECTORY
    if not corpus.is_dir():
        return []
    return sorted(
        (path for path in corpus.rglob("*.md") if path.is_file() and path.name != INDEX_NAME),
        key=lambda path: path.relative_to(root).as_posix().casefold(),
    )


def _workspace_markdown_files(root: Path) -> list[Path]:
    return sorted(
        (path for path in root.rglob("*.md") if path.is_file() and ".git" not in path.relative_to(root).parts and path.name != INDEX_NAME),
        key=lambda path: path.relative_to(root).as_posix().casefold(),
    )


def _content_type_for_path(path: Path, root: Path) -> str | None:
    try:
        relative = path.relative_to(root / BRAIN_DIRECTORY).as_posix()
    except ValueError:
        return None
    for directory, document_type in CONTENT_DIRECTORIES.items():
        if relative.startswith(directory + "/"):
            return document_type
    return None


def build_index(root: Path) -> str:
    """Build deterministic local Index content from Engram only."""
    root = root.resolve()
    entries: list[IndexEntry] = []
    for path in _corpus_markdown_files(root):
        parsed = parse_frontmatter(read_utf8(path))
        metadata = parsed.metadata if not parsed.error else {}
        body = parsed.body if parsed.has_frontmatter else read_utf8(path)
        topics = tuple(_metadata_strings(metadata.get("topics")))
        entries.append(IndexEntry(
            document_type=str(metadata.get("type") or "context").replace("-", " ").title(),
            title=_first_h1(body) or path.stem,
            status=str(metadata.get("status") or ""),
            topics=topics,
            summary=_first_summary(body),
            relative_path=path.relative_to(root / BRAIN_DIRECTORY).as_posix(),
        ))
    grouped: dict[str, list[IndexEntry]] = defaultdict(list)
    for entry in entries:
        grouped[entry.document_type].append(entry)
    lines = [
        "# Team Engram Index",
        "",
        GENERATED_MARKER,
        "",
        "This local file is generated deterministically from `Engram/`.",
    ]
    if not entries:
        lines.extend(["", "_No corpus pages found._"])
    for document_type in sorted(grouped, key=str.casefold):
        lines.extend(["", f"## {document_type}"])
        for entry in sorted(grouped[document_type], key=lambda item: (item.title.casefold(), item.relative_path.casefold())):
            label = entry.title.replace("\\", "\\\\").replace("]", "\\]")
            line = f"- [{label}]({quote(entry.relative_path, safe='/@:+-._~')})"
            if entry.status:
                line += f" — status: `{_clean_inline_markdown(entry.status)}`"
            if entry.topics:
                line += f" — topics: `{', '.join(entry.topics)}`"
            if entry.summary:
                line += f" — {entry.summary}"
            lines.append(line)
    return "\n".join(lines) + "\n"


def update_index(root: Path, check: bool = False) -> int:
    expected = build_index(root)
    index_path = root / BRAIN_DIRECTORY / INDEX_NAME
    if check:
        if not index_path.exists():
            print(f"ERROR: {BRAIN_DIRECTORY}/{INDEX_NAME} is missing", file=sys.stderr)
            return 1
        if read_utf8(index_path) != expected:
            print(f"ERROR: {BRAIN_DIRECTORY}/{INDEX_NAME} is stale; run 'python Tools/engram.py index'", file=sys.stderr)
            return 1
        print(f"OK: {BRAIN_DIRECTORY}/{INDEX_NAME} is up to date")
        return 0
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {BRAIN_DIRECTORY}/{INDEX_NAME} ({len(_corpus_markdown_files(root))} documents)")
    return 0


def _markdown_link_destinations(text: str) -> Iterable[tuple[int, str]]:
    pattern = re.compile(r"!?\[[^\]\n]*\]\(\s*(<[^>]+>|[^\s)]+)(?:\s+['\"][^)]*['\"])?\s*\)")
    reference = re.compile(r"^\s*\[[^\]]+\]:\s*(<[^>]+>|\S+)")
    in_fence = False
    for line_number, raw_line in enumerate(text.splitlines(), 1):
        if re.match(r"^\s*(```|~~~)", raw_line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        line = re.sub(r"`[^`]*`", "", raw_line)
        for match in pattern.finditer(line):
            yield line_number, match.group(1)
        match = reference.match(line)
        if match:
            yield line_number, match.group(1)


def _relative_link_target(source: Path, destination: str) -> Path | None:
    destination = destination.strip().strip("<>")
    if not destination or destination.startswith("#"):
        return None
    split = urlsplit(destination)
    if split.scheme or split.netloc or destination.startswith(("/", "\\")) or re.match(r"^[A-Za-z]:[\\/]", destination):
        return None
    return (source.parent / unquote(split.path).replace("/", os.sep)).resolve() if split.path else None


def _display(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def _field_issue(path: Path, message: str) -> LintIssue:
    return LintIssue("ERROR", path, 1, message)


def _validate_schema_page(path: Path, root: Path, parsed: FrontMatter, schema: dict[str, Any]) -> list[LintIssue]:
    issues: list[LintIssue] = []
    expected_type = _content_type_for_path(path, root)
    if expected_type is None:
        return issues
    metadata = parsed.metadata
    if not parsed.has_frontmatter:
        return [_field_issue(path, "corpus page is missing YAML frontmatter")]
    if parsed.error:
        return issues
    document_type = metadata.get("type")
    if document_type not in schema["types"]:
        issues.append(_field_issue(path, f"unknown type '{document_type}'"))
        return issues
    if document_type != expected_type:
        issues.append(_field_issue(path, f"type '{document_type}' does not match directory type '{expected_type}'"))
    definition = schema["types"][document_type]
    for field in schema["common_required"] + definition.get("required", []):
        if not _is_meaningful(metadata.get(field)):
            issues.append(_field_issue(path, f"missing required field '{field}'"))
    status = metadata.get("status")
    if status not in definition["statuses"]:
        issues.append(_field_issue(path, f"invalid status '{status}' for type '{document_type}'"))
    topics = metadata.get("topics")
    if topics is not None and not isinstance(topics, list):
        issues.append(_field_issue(path, "field 'topics' must be a list"))
    if status == "superseded" and not _is_meaningful(metadata.get("superseded_by")):
        issues.append(_field_issue(path, "status 'superseded' requires field 'superseded_by'"))
    if document_type == "decision":
        identifier = metadata.get("id")
        if isinstance(identifier, str) and not re.fullmatch(definition["id_pattern"], identifier):
            issues.append(_field_issue(path, f"invalid decision id '{identifier}'"))
        date_value = metadata.get("date")
        if _is_meaningful(date_value) and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(date_value)):
            issues.append(_field_issue(path, "field 'date' must use YYYY-MM-DD"))
    if document_type in {"decision", "source-raw", "source-record"}:
        date_field = "date" if document_type == "decision" else "retrieved"
        value = metadata.get(date_field)
        if _is_meaningful(value) and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(value)):
            issues.append(_field_issue(path, f"field '{date_field}' must use YYYY-MM-DD"))
    if document_type == "source-raw":
        artifact_values = _metadata_strings(metadata.get("artifact_path"))
        if _is_meaningful(metadata.get("artifact_path")) and not artifact_values:
            issues.append(_field_issue(path, "artifact_path must be a string or list of strings"))
        if artifact_values and not _is_meaningful(metadata.get("content_hash")):
            issues.append(_field_issue(path, "artifact_path requires content_hash"))
        for artifact_value in artifact_values:
            normalized = unquote(artifact_value).replace("\\", "/")
            candidate = (root / normalized).resolve() if normalized.startswith("Engram/") else (path.parent / normalized).resolve()
            raw_root = (root / "Engram/Sources/Raw").resolve()
            try:
                candidate.relative_to(raw_root)
            except ValueError:
                issues.append(_field_issue(path, "artifact_path points outside Engram/Sources/Raw"))
                continue
            if not candidate.is_file():
                issues.append(_field_issue(path, f"artifact_path does not exist: {artifact_value}"))
                continue
            hash_value = str(metadata.get("content_hash") or "")
            match = re.fullmatch(r"sha256:([0-9a-fA-F]{64})", hash_value)
            if not match:
                issues.append(_field_issue(path, "content_hash must use sha256:<64 hexadecimal characters>"))
            elif hashlib.sha256(candidate.read_bytes()).hexdigest().casefold() != match.group(1).casefold():
                issues.append(_field_issue(path, f"content_hash does not match artifact: {artifact_value}"))
    if document_type == "source-record":
        materials = _metadata_strings(metadata.get("raw_materials"))
        if not materials:
            issues.append(_field_issue(path, "field 'raw_materials' must link to at least one raw record"))
        for material in materials:
            match = re.fullmatch(r"\[[^]]+\]\(([^)]+)\)", material)
            if not match:
                issues.append(_field_issue(path, "raw_materials entries must be Markdown links"))
                continue
            target = _relative_link_target(path, match.group(1))
            raw_root = (root / "Engram/Sources/Raw").resolve()
            if target is None:
                issues.append(_field_issue(path, "raw_materials must use relative links to Engram/Sources/Raw"))
                continue
            try:
                target.relative_to(raw_root)
            except ValueError:
                issues.append(_field_issue(path, "raw_materials link points outside Engram/Sources/Raw"))
            if not target.is_file():
                issues.append(_field_issue(path, f"raw_materials link does not exist: {match.group(1)}"))
    if not _first_h1(parsed.body):
        issues.append(_field_issue(path, "corpus page must contain a level-one heading"))
    return issues


def lint_workspace(root: Path) -> list[LintIssue]:
    """Return deterministic schema and Markdown-link findings without writing."""
    root = root.resolve()
    issues: list[LintIssue] = []
    try:
        schema = load_schema(root)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        return [_field_issue(root / SCHEMA_PATH, f"cannot load schema: {error}")]
    decision_locations: dict[str, list[Path]] = defaultdict(list)
    referenced_artifacts: set[Path] = set()
    for path in _workspace_markdown_files(root):
        try:
            text = read_utf8(path)
        except (OSError, UnicodeError) as error:
            issues.append(LintIssue("ERROR", path, 1, f"cannot read UTF-8 text: {error}"))
            continue
        parsed = parse_frontmatter(text)
        if parsed.error:
            issues.append(LintIssue("ERROR", path, parsed.error_line or 1, f"malformed frontmatter: {parsed.error}"))
        issues.extend(_validate_schema_page(path, root, parsed, schema))
        if _content_type_for_path(path, root) == "source-raw":
            for artifact_value in _metadata_strings(parsed.metadata.get("artifact_path")):
                normalized = unquote(artifact_value).replace("\\", "/")
                candidate = (root / normalized).resolve() if normalized.startswith("Engram/") else (path.parent / normalized).resolve()
                referenced_artifacts.add(candidate)
        if _content_type_for_path(path, root) == "decision":
            identifier = parsed.metadata.get("id")
            if isinstance(identifier, str) and identifier:
                decision_locations[identifier.upper()].append(path)
        for line_number, destination in _markdown_link_destinations(text):
            target = _relative_link_target(path, destination)
            if target is not None and not target.exists():
                issues.append(LintIssue("ERROR", path, line_number, f"broken relative link: {destination.strip('<>')}"))
    raw_root = root / "Engram" / "Sources" / "Raw"
    if raw_root.is_dir():
        for artifact in sorted((path for path in raw_root.rglob("*") if path.is_file() and path.name != ".gitkeep" and path.suffix.casefold() != ".md"), key=lambda path: path.as_posix().casefold()):
            if artifact.resolve() not in referenced_artifacts:
                issues.append(_field_issue(artifact, "raw artifact has no source-raw manifest with artifact_path"))
    for identifier, paths in sorted(decision_locations.items()):
        if len(paths) > 1:
            locations = ", ".join(_display(path, root) for path in paths)
            issues.append(_field_issue(paths[0], f"duplicate decision ID {identifier}: {locations}"))
    severity_order = {"ERROR": 0, "WARN": 1}
    return sorted(issues, key=lambda issue: (severity_order.get(issue.severity, 9), _display(issue.path, root).casefold(), issue.line, issue.message.casefold()))


def print_lint(root: Path) -> int:
    issues = lint_workspace(root)
    for issue in issues:
        print(f"{issue.severity} {_display(issue.path, root)}:{issue.line} {issue.message}")
    errors = sum(issue.severity == "ERROR" for issue in issues)
    warnings = sum(issue.severity == "WARN" for issue in issues)
    print(f"Lint: {errors} error(s), {warnings} warning(s)")
    return 1 if errors else 0


def _markdown_count(directory: Path) -> int:
    return sum(1 for path in directory.rglob("*.md") if path.is_file()) if directory.is_dir() else 0


def status_lines(root: Path) -> list[str]:
    engram = root / BRAIN_DIRECTORY
    return [
        f"Knowledge: {_markdown_count(engram / 'Knowledge')}",
        f"Decisions: {_markdown_count(engram / 'Decisions')}",
        f"Sources: raw={_markdown_count(engram / 'Sources' / 'Raw')}, records={_markdown_count(engram / 'Sources' / 'Records')}",
    ]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="engram.py", description="Dependency-free local maintenance for Team Engram.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    index_parser = subparsers.add_parser("index", help="generate local deterministic Engram/INDEX.md")
    index_parser.add_argument("--check", action="store_true", help="fail if the local Index is missing or stale")
    subparsers.add_parser("lint", help="run read-only schema and Markdown checks")
    subparsers.add_parser("status", help="show compact team corpus counts")
    return parser


def main(argv: Sequence[str] | None = None, root: Path | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    actual_root = (root or workspace_root()).resolve()
    try:
        if arguments.command == "index":
            return update_index(actual_root, check=arguments.check)
        if arguments.command == "lint":
            return print_lint(actual_root)
        if arguments.command == "status":
            print("\n".join(status_lines(actual_root)))
            return 0
    except (OSError, UnicodeError, ValueError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
